### PR TITLE
Update test fixtures, Ruby version and dependencies.

### PR DESCRIPTION
**Pull request by tingulfsen**
This pull request updates the test fixtures to be in line with the output from the latest version of the MODSulator gem.

It also updates the dependencies to use the latest possible versions of everything.

### CODE REVIEW

**Comment by tingulfsen** [comment]
Note that we're also upgrading everything to Ruby 2.2.4 - the latest stable Ruby at this time.

**Comment by mjgiarlo** [comment]
@tingulfsen Other than 2.3.0, of course!

**Comment by tingulfsen** [comment]
Good point, @mjgiarlo - do you see any issues with choosing Ruby 2.4.0 in production at this time, instead of 2.3.0?

**Comment by mjgiarlo** [comment]
2.4.0? Do you mean 2.2.4? I suspect you'll be fine with either. :)

**Pull request merged**
